name: OCaml checks

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '4.14'
      - run: opam install yojson dune -y
      - run: opam exec -- dune build @all
      - run: opam exec -- dune runtest --force
